### ISSUE TITLE
Cut a new release with crate_version

### ISSUE THREAD

**Issue by moritzheiber** [onatm/kx#1]
Love [the use of `crate_version` here](https://github.com/onatm/kx/commit/34ed4040079a9342708c8438a2836dbf8ab83534) as it makes it possible to install `kx` with popular configuration management tooling. However, would you be able to cut a new release with it enabled? It would make my life a little easier installing and using it :slightly_smiling_face: 

Thanks!

**Comment by onatm** [comment]
Hey @moritzheiber, thank you for opening this issue. I will release a new version ASAP.

**Comment by onatm** [comment]
I've just released the new version. Could you please install and verify it @moritzheiber?

```sh
cargo install kx
```

**Comment by moritzheiber** [comment]
Done. Works. Solved!
