### ISSUE TITLE
Release has tar.gz extension but file is not gzipped

### ISSUE THREAD

**Issue by ottolote** [onatm/kx#2]
Firstly, thanks for making this :+1: 

kx-v1.2.0-linux-amd64.tar.gz is not in gzip format but has .gz extension

For clarity:
- Running `tar -zxvf kx-v1.2.0-linux-amd64.tar.gz` or `gunzip kx-v1.2.0-linux-amd64.tar.gz` both result in:
```
gzip: kx-v1.2.0-linux-amd64.tar.gz: not in gzip format
```

- Running `tar -xvf kx-v1.2.0-linux-amd64.tar.gz` (tar without -z) works as expected

**Comment by onatm** [comment]
Hey @ottolote,

Happy to hear that you find this useful and thank you for bringing this to my attention.

I'll fix it hopefully this weekend.

**Comment by onatm** [comment]
We have a new release with properly gzipped archives: https://github.com/onatm/kx/releases/tag/v1.3.0
